[build]
  functions = "functions"

[[redirects]]
  from = "/recipe/*"
  to = "/.netlify/functions/getRecipe"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200